#!/usr/bin/env python3
"""
NVCC Blackwell IR Extractor

Compiles CUDA code strictly for NVIDIA Blackwell (sm_100/sm_100a) and
aggressively extracts all IR artifacts: PTX, SASS, cubin, fatbin, etc.
"""

import argparse
import glob
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

# Regex for precise stem matching: matches "base.ext" and "base.<tag>.ext"
# e.g. for stem="kernel", ext=".cubin":
#   ✓ kernel.cubin, kernel.sm_100.cubin, kernel.1.sm_100a.cubin
#   ✗ kernel2.cubin, kernel_old.cubin
_STEM_RE_CACHE: dict[str, re.Pattern[str]] = {}


def _stem_glob(directory: str, base_name: str, ext: str) -> list[str]:
    """Find files matching `base_name[.<tag>...]ext` precisely.

    Uses two globs to cover both direct naming (base.ext) and nvcc's
    intermediate naming (base.<tag>.ext like kernel.sm_100.cubin).
    Validates results with regex to reject false positives like
    kernel2.cubin or kernel_old.cubin.
    """
    key = f"{base_name}|{ext}"
    if key not in _STEM_RE_CACHE:
        # Match: base_name + optional (.<anything>)* + ext
        _STEM_RE_CACHE[key] = re.compile(
            rf"^{re.escape(base_name)}(\..*)?{re.escape(ext)}$"
        )
    pattern = _STEM_RE_CACHE[key]

    candidates: list[str] = []
    # Glob 1: direct match (e.g. kernel.cubin)
    candidates.extend(glob.glob(os.path.join(directory, f"{base_name}{ext}")))
    # Glob 2: tagged match (e.g. kernel.sm_100.cubin)
    candidates.extend(
        glob.glob(os.path.join(directory, f"{base_name}.*{ext}"))
    )

    # Deduplicate and validate against the precise regex
    seen: set[str] = set()
    result: list[str] = []
    for path in candidates:
        abs_path = os.path.abspath(path)
        if abs_path in seen:
            continue
        seen.add(abs_path)
        filename = os.path.basename(path)
        if pattern.match(filename):
            result.append(path)
    return result


def _filter_new_files(
    paths: list[str],
    pre_existing: set[str] | None = None,
) -> list[str]:
    """Keep only files created by the current invocation."""
    if not pre_existing:
        return paths
    return [path for path in paths if os.path.abspath(path) not in pre_existing]


def check_prerequisites() -> None:
    """Verify that nvcc and cuobjdump are available in PATH."""
    missing: list[str] = []

    if not shutil.which("nvcc"):
        missing.append("nvcc")
    if not shutil.which("cuobjdump"):
        missing.append("cuobjdump")

    if missing:
        tools = ", ".join(missing)
        print(f"✗ Required tool(s) not found in PATH: {tools}")
        print()
        print("To fix this:")
        print("  1. Install the NVIDIA CUDA Toolkit: https://developer.nvidia.com/cuda-downloads")
        print("  2. Ensure the toolkit bin/ directory is in your PATH, e.g.:")
        print("     export PATH=/usr/local/cuda/bin:$PATH")
        sys.exit(1)


def run_nvcc(input_file: str, arch: str, output_dir: str, extra_options: str) -> int:
    """Run nvcc with Blackwell-specific flags. Returns the process returncode."""
    nvcc_cmd: list[str] = [
        "nvcc",
        f"-arch={arch}",
        # retain all intermediate files (.ptx, .cubin, .fatbin, etc.)
        "--save-temps",
        "-Xptxas=-v",          # verbose ptxas output (registers, spills, smem)
        "-lineinfo",           # line-number info for profiling / source correlation
        # redirect intermediate files to output dir
        f"--keep-dir={output_dir}",
        "-c", input_file,      # compile to object, don't link
        # explicit output path to ensure .o goes to output_dir
        "-o", os.path.join(output_dir, Path(input_file).stem + ".o"),
    ]

    if extra_options:
        # NOTE: shlex.split uses POSIX semantics; this script targets
        # macOS / Linux only.  Windows users would need different handling.
        nvcc_cmd.extend(shlex.split(extra_options, posix=True))

    cmd_str = shlex.join(nvcc_cmd)  # shell-safe: handles paths with spaces
    print("=" * 60)
    print(f"Executing NVCC Command:\n{cmd_str}")
    print("=" * 60)

    result = subprocess.run(nvcc_cmd, capture_output=True, text=True)

    if result.stdout:
        print(result.stdout)
    if result.stderr:
        # nvcc/ptxas info is often printed to stderr
        print(result.stderr)

    if result.returncode != 0:
        print("✗ NVCC Compilation failed.")
    else:
        print("✓ NVCC Compilation successful.")

    return result.returncode


def extract_sass(
    output_dir: str,
    base_name: str,
    pre_existing: set[str] | None = None,
) -> None:
    """Extract SASS from cubin files generated by the current compilation.

    Args:
        output_dir: Primary directory to search for cubin files.
        base_name: Stem of the input file (e.g. 'kernel' for 'kernel.cu').
        pre_existing: Paths that existed before compilation (filtered out).
    """
    cubin_files = _filter_new_files(
        _stem_glob(output_dir, base_name, ".cubin"),
        pre_existing,
    )

    cwd = os.path.abspath(".")
    if os.path.abspath(output_dir) != cwd:
        # Some nvcc versions still drop artifacts in CWD even with --keep-dir.
        seen = {os.path.abspath(path) for path in cubin_files}
        for cubin_file in _filter_new_files(
            _stem_glob(".", base_name, ".cubin"),
            pre_existing,
        ):
            abs_path = os.path.abspath(cubin_file)
            if abs_path not in seen:
                seen.add(abs_path)
                cubin_files.append(cubin_file)

    if not cubin_files:
        print(
            f"\nWarning: No .cubin files found matching '{base_name}[.*].cubin'.")
        return

    for cubin_file in cubin_files:
        sass_file = str(Path(cubin_file).with_suffix(".sass"))
        print(f"\nExtracting SASS from {cubin_file}...")

        try:
            sass_result = subprocess.run(
                ["cuobjdump", "-sass", cubin_file],
                capture_output=True,
                text=True,
                check=True,
            )
            Path(sass_file).write_text(sass_result.stdout, encoding="utf-8")
            print(f"✓ SASS extraction successful -> {sass_file}")
        except subprocess.CalledProcessError as e:
            print(f"✗ Failed to extract SASS from {cubin_file}: {e.stderr}")


def list_artifacts(
    output_dir: str,
    base_name: str,
    pre_existing: set[str] | None = None,
) -> None:
    """List all artifacts generated by the current compilation.

    Args:
        output_dir: Primary directory to search for artifacts.
        base_name: Stem of the input file (e.g. 'kernel' for 'kernel.cu').
        pre_existing: Optional set of absolute paths that existed before
                      compilation.  Applied to BOTH output_dir and CWD
                      to filter out stale artifacts from previous runs.
    """
    print("\n" + "=" * 60)
    print("Generated Artifacts (this run only):")
    print("=" * 60)

    extensions = [
        ".ptx", ".cubin", ".sass", ".ii",
        ".cudafe1.c", ".cudafe1.cpp", ".cudafe1.gpu",
        ".fatbin", ".fatbin.c", ".module_id", ".o", ".obj",
    ]

    found: list[tuple[str, int, str]] = []  # (path, size, source)
    seen: set[str] = set()

    def _collect(directory: str, source_label: str) -> None:
        for ext in extensions:
            for filepath in _stem_glob(directory, base_name, ext):
                abs_path = os.path.abspath(filepath)
                if abs_path in seen:
                    continue
                seen.add(abs_path)
                # Skip files that existed before this compilation
                if pre_existing and abs_path in pre_existing:
                    continue
                size = os.path.getsize(filepath)
                found.append((filepath, size, source_label))

    # Primary: search output_dir
    _collect(output_dir, "output-dir")

    # Fallback: search CWD (in case nvcc dropped something here)
    _collect(".", "cwd-fallback")

    found.sort(key=lambda x: x[0])

    for filepath, size, source in found:
        label = " [fallback: CWD]" if source == "cwd-fallback" else ""
        print(f"  - {filepath} ({size} bytes){label}")

    if not found:
        print("  (No artifacts found matching the expected names)")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract IR and Assembly for NVIDIA Blackwell (sm_100/sm_100a)"
    )
    parser.add_argument(
        "--input", "-i", required=True,
        help="Input CUDA source file (.cu)",
    )
    parser.add_argument(
        "--arch", "-a", default="sm_100",
        choices=["sm_100", "sm_100a"],
        help="Target architecture (default: sm_100). Use sm_100a for arch-specific features.",
    )
    parser.add_argument(
        "--output-dir", "-d", default="./blackwell_ir_output",
        help="Directory to store intermediate files (default: ./blackwell_ir_output)",
    )
    parser.add_argument(
        "--options", default="",
        help="Additional nvcc options to append",
    )

    args = parser.parse_args()

    # --- Validate input ---
    if not os.path.exists(args.input):
        print(f"✗ Error: Input file '{args.input}' not found.")
        sys.exit(1)

    # --- Check tools ---
    check_prerequisites()

    # --- Prepare output directory ---
    os.makedirs(args.output_dir, exist_ok=True)

    input_path = Path(args.input)
    base_name = input_path.stem

    # --- Snapshot existing files in BOTH output_dir and CWD ---
    # This lets us filter out stale artifacts from previous compilations.
    pre_existing: set[str] = set()
    for directory in (args.output_dir, "."):
        for f in os.listdir(directory):
            pre_existing.add(os.path.abspath(os.path.join(directory, f)))

    # --- Compile ---
    returncode = run_nvcc(args.input, args.arch, args.output_dir, args.options)
    if returncode != 0:
        sys.exit(returncode)

    # --- Extract SASS ---
    extract_sass(args.output_dir, base_name, pre_existing)

    # --- List artifacts ---
    list_artifacts(args.output_dir, base_name, pre_existing)


if __name__ == "__main__":
    main()
